openapi: 3.0.1
info:
  title: Exchange application
  version: "0.1.0"
servers:
  - url: http://localhost:8080
paths:
  /api/json/{currency}:
    get:
      tags:
      - exchange-controller
      operationId: json
      parameters:
      - name: currency
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exchange'
        "404":
          description: Not found
        "500":
          description: Server error

  /api/gif/{currency}:
    get:
      tags:
      - exchange-controller
      operationId: gif
      parameters:
      - name: currency
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            image/gif:
              schema:
                type: array
                items:
                  type: string
                  format: byte
        "404":
          description: Not found
        "500":
          description: Server error

components:
  schemas:
    Exchange:
      type: object
      properties:
        yesterday:
          type: number
          minimum: 0.0
          exclusiveMinimum: false
          format: double
        latest:
          type: number
          minimum: 0.0
          exclusiveMinimum: false
          format: double
        gifUrl:
          type: string
        query:
          type: string
          enum:
            - rich
            - broke
